services:

  # ROS Galactic
  rviz:
    image: husarion/rviz2:galactic
    runtime: nvidia
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_pro_mapping.rviz:/root/.rviz2/default.rviz
      # - ./config/rosbot_pro_localization.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  # ROS Galactic
  nav2:
    image: husarion/nav2:galactic
    volumes: 
      - ./config:/ros2_ws/src/husarion_nav2/config
    command: >
      ros2 launch husarion_nav2 navigation2_bringup.launch.py
        use_slam:=True 
        use_sim_time:=True

  bridge:
    build:
      context: ./
      dockerfile: ./Dockerfile.bridge
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: ros2 run ros1_bridge dynamic_bridge

  # ROS Melodic master
  ros-master:
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore

  # ROS Melodic
  rosbot_simulation:
    image: husarion/rosbot:melodic-simulation
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../src/rosbot_navigation/maps:/ros_ws/src/rosbot_navigation/maps
    command: roslaunch rosbot_description rosbot_rviz_gmapping.launch --wait