services:
  
  # ROS Melodic Orbbec Astra docker
  astra:
    image: husarion/astra:latest
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    devices:
      - /dev/bus/usb/001/005
    tty: true        
    command: roslaunch astra_camera astra.launch