services:

  # ROS Melodic
  navigation:
    image: husarion/rosbot:melodic-simulation
    container_name: amcl-melodic
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: roslaunch --wait rosbot_navigation amcl_demo.launch
