services:

  rviz:
    network_mode: service:husarnet-pc
    depends_on:
      - husarnet-pc
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - ROS_DOMAIN_ID=228
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds-config.xml
      
  husarnet-pc:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz
      - JOINCODE=${HUSARNET_JOINCODE}